Try to improve React dependencies handling
skatejs/build pull request #403
Opened 2016-10-03 16:30 UTC by zzarcon

Changes are related to https://github.com/skatejs/skatejs/pull/808. Regarding the **benchmark** library, I just removed from the `files` since we are not using the [bench file](https://github.com/skatejs/skatejs/blob/master/test/lib/bench.js), if we want to add it again we can just put it as a npm dependency.

2016-10-03 23:14 UTC, treshugart requested changes
Could you also make sure your commits follow conventional changelog please (git cz or sk-commit)? Thanks!

2016-10-03 23:14 UTC, treshugart commented on webpack.config.js
> +    new webpack.DefinePlugin({
This should probably only be enabled in `--perf` mode.

2016-10-05 20:55 UTC, zzarcon commented on webpack.config.js
> +    new webpack.DefinePlugin({
Good point

2016-10-05 21:23 UTC, zzarcon commented
@treshugart I applied the changes and committed them using `git cz` properly, let me know if it's fine now

2016-10-06 22:25 UTC, treshugart approved these changes

2016-10-06 22:25 UTC, merged